version = 1
SPDX-PackageName = "example-content"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/example-content"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and openMFP contributors and example-content contributors."
SPDX-License-Identifier = "Apache-2.0"
