{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - {{ .Release.Namespace }}/gateway
  hosts:
  - {{ .Values.subdomain }}.d1.openmfp.dxp.k8s.ondemand.com
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
    route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
{{- end -}}