apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
spec:
  inlineConfiguration:
    content: |-
      {{ .Files.Get "assets/accounts.json" | nindent 6 }}
    contentType: json
