{{- if .Values.contentConfigurations.infra }}
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: infra
  namespace: {{ .Release.Namespace }}
spec:
  inlineConfiguration:
    content: |-
      {{ .Files.Get "assets/infra.json" | nindent 6 }}
    contentType: json
{{- end }}