image:
  name: ghcr.io/openmfp/example-content
  pullPolicy: IfNotPresent
  pullSecret: github

deployment:
  maxUnavailable: 0
  maxSurge: 5

port: 8080

istio:
  enabled: true

subdomain: content

http:
  protocol: https
