name: pipe
on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/example-ui
      componentVersionKey: example-ui
      release_branch: wip
      chartFolder: charts/example-ui
      additionalTestFilesCommand: -f charts/example-ui/test-values.yaml