name: pipe
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@8ab150881aeeecfc088878622eb2cd862e4c9cf2 # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/example-content
      componentVersionKey: example-content
      repoVersionUpdate: openmfp/helm-charts
      node_version: "24"