name: pipe
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@82b078aff8e5a415bbcc1261b63fa1a3f4a9b49c # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/example-content
      componentVersionKey: example-content
      repoVersionUpdate: openmfp/helm-charts