name: pipe
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@27d6784ac793ef690bd3c02ecfb047711394cfcb # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/example-content
      componentVersionKey: example-content
      repoVersionUpdate: openmfp/helm-charts