name: pipe
on:
  push:
    branches:
      - apeirora
  pull_request:
    branches:
      - apeirora

concurrency:
  group: apeirora-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@feat-improve-tagging
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/apeirora-example-content
      componentVersionKey: apeirora-example-content
      release_branch: apeirora
      versionPrefix: 'apeirora-'